### ISSUE TITLE
login with ssh key to KVM server

### ISSUE THREAD

**Issue by steve-netskope** [mistio/mist.io#472]
I can login with ssh keys but when the key is added to Mist, it cannot logon (KVM libvirt). Below is the error. What would be a suggested way to troubleshoot?

2015-04-29 17:56:46,340 ERROR MainThread methods - add_backend_v_2: Error while adding backendException('Make sure ssh key and username are valid',)
2015-04-29 17:56:46,341 INFO MainThread views - exception_handler_mist: MistError: BackendUnavailableError("Backend unavailable: Exception('Make sure ssh key and username are valid',)",)
[pid: 1393|app: 0|req: 201/614] 127.0.0.1 () {52 vars in 864 bytes} [Wed Apr 29 17:56:46 2015] POST /backends => generated 75 bytes in 216 msecs (HTTP/1.1 503) 2 headers in 96 bytes (1 switches on core 0)

**Comment by mgogoulos** [comment]
Hi Steve, 

this error indicates that you try to add a KVM cloud, but provide an invalid username/ssh key combination. Please make sure the combination is valid.

If you specify a valid user/key, but the user has no rights to the libvirt daemon running  you are going to receive a different error this time: "Make sure libvirt is running and user X is authorised to connect". Usually the user needs to be root or priviledged user in order to connect to libvirt

If you are running a local installation of mist.io, you can perform some debugging by running cloudpy:

```
user@user:~/Desktop/mist.io$ ./bin/cloudpy 
Python 2.7.4 (default, Sep 26 2013, 03:20:26) 
In [1]: from libcloud.compute.providers import get_driver; driver = get_driver('libvirt')
In [2]: c = driver('kvm-host', 'root', 'path_to_ssh_key')
```
if you provide the correct credentials (user/ssh key) for a user on kvm-host that can communicate with libvirt, then this will not raise any exceptions. Provide the same credentials on mist.io's add cloud menu

Cheers,
Markos
