### ISSUE TITLE
No ability to log-out of own instance

### ISSUE THREAD

**Issue by KeiroD** [mistio/mist.io#475]
Hi,

So, after having finally gotten a proper working mist.io instance up and running, I notice a glaring issue:

If you visit a freshly-installed instance and try logging in, there is NO capability for logging out of a logged-in account. Or worse, having no capability to ensure that only you have access to your own running instance.

Your documentation reveals basically nothing about what to do if you decide to download the open-source version of mist.io.

This is a critical security issue that needs to be resolved ASAP. How did you guys not notice this?

**Comment by Clopy** [comment]
Hi Keiro, 

The open-source version doesn't have user management or authentication support. It is just the infrastructure management interface. If you need authentication and to hide the interface from plain sight, you could use http auth behind apache or nginx.

If you're looking for the full multi-user service to act as a reseller, like the one on https://mist.io I can hook you up with one of our sales managers to discuss licensing.

**Comment by KeiroD** [comment]
@Clopy 

I think not having authentication or user management in your open-source version is a very bad idea.

At least include authentication support in the open-source version to prevent anyone finding a user's mist.io instance and doing very bad things to it. Charge for user management if you must, but for the love of all that's good security-wise, please include some form of authentication support.

**Comment by JanLoebel** [comment]
I would agree with @KeiroD . At least providing a hook point to add custom authentication modules provided by the community would be really great. I get the point that you want to earn money with the system itself. But at least a small authentication step like one defined user (admin/admin) defined in a file would be very easy to implement.

**Comment by mgogoulos** [comment]
Hi JanLoebel, 

the open source version starts on the localhost interface, so this poses no security threat. It is then easy to expose it to some other interface and also add some http auth through nginx or through haproxy for this. You are more than welcome to contribute in the FAQ section (or in an article) about how to add basic auth on nginx or even better haproxy - since it is used by mist.io.

 At this point we are not thinking of adding auth modules of some sort to mist.io because we want to get it done correctly on the Saas. We are adding role based access control functionality and team support for the Saas, which means that teams and organizations can be created, or imported through SSO systems. On the same time we are moving fast functionality from the Saas to the open source version (scripts, monitoring, logs).

Regards,
Markos

**Comment by mgogoulos** [comment]
Version 2 is out, comes with an easier installation process using Docker Compose and many new features, check updated instructions on https://github.com/mistio/mist.io

This also includes user management!

**Comment by mgogoulos** [comment]
blog.mist.io/post/162083041316/our-biggest-mistio-open-source-release-yet
