### ISSUE TITLE
Yikes - local mist.io installation is open to everyone

### ISSUE THREAD

**Issue by fuqqer** [mistio/mist.io#476]
The mistio frontend is not locked down to only localhost!  That means anyone could point their browser at my machine while mist.io is running and manage every resource my installation of mist.io can.  Yikes!

**Comment by Clopy** [comment]
Hi fuqqer,

mist.io is not meant to be installed in a publicly accesible machine without some kind of authentication in front of it. We will discuss with the rest of  the dev team if we can add some kind of basic authentication, since others have requested it. In your case, probably the simplest solution would be to add basic http authentication via apache or nginx. 

I will add a section to the install doc to clarify that people should not leave it publicly accesible without some means of lockdown or authentication.

Thanks!

**Comment by mgogoulos** [comment]
Mist.io will now start on the localhost interface only (https://github.com/mistio/mist.io/commit/43a5145111b6b2c6278174a0758a394546bf0121). You can setup haproxy to listen on 0.0.0.0 by editing  haproxy.conf file and restarting haproxy

```
$vi haproxy.conf
```

change : frontend www localhost:8000  to frontend www 0.0.0.0:8000
and restart haproxy

```
$ ./bin/supervisorctl restart haproxy
```
