### ISSUE TITLE
scripts

### ISSUE THREAD

**Issue by bryfry** [mistio/mist.io#512]
On the main dashboard page there is no place to manage scripts.  Is this intentionally not a part of the open source project?  From the install and documentation I expected ansible to be able to run playbooks on my instances.  What gives?

**Comment by mgogoulos** [comment]
Hi, 

the functionality to add and run executable scripts and ansible playbooks (via an inline editor, import from github repository or a single URL containing a file or zip/tar archive) is provided in the SaaS (https://mist.io) only at the moment.  You just need to have an account on the SaaS in order to use this feature - no need to be subscribed on a plan. 

We are thinking of providing that feature on the open source project as well but I cannot comment on the time this will be implemented. 

Regards,
Markos

**Comment by svx** [comment]
+1 if it would be possible to add this to the open source version !

**Comment by cpsaltis** [comment]
Hey a fellow Plone fan, nice to meet you @svx 

Could you elaborate a bit on your use case here?

**Comment by svx** [comment]
Hi,

sorry vacation :)

Well our use case is that we are using the open source version, since we are using Ansible too it would be great if it would be able to use it from the same setup.

:)

We use mist.io for internal deploys, so using the hosted version in not possible for us.

**Comment by cpsaltis** [comment]
I hope you had a great time :)

What's your infrastructure stack like? What do you do regarding monitoring? Would you be interested in orchestration, workflows and/or RBAC?

I'm asking because most of these are coming in the open source version, together with scripts and script scheduling. Some will remain only in the paid on-prem and SaaS versions.

**Comment by svx** [comment]
Yes, thanks I had !

We use a mix of KVM, Docker, rkt and LXCD, depends on the service/setup

Monitoring is done via sensu.

WOW sounds awesome, that lots of the stuff is coming into the open source version.

Workflows, orchestration and such would be a huge plus, too !

WOW, we are looking forward to it ! :)

Thanks for all your effort !

**Comment by cpsaltis** [comment]
Yeah lot's of cool stuff coming up, yet lots and lots of work... That's why it will take some time.

What infrastructure size are we talking about here? 10s of VM and 100s of containers?

Interesting mix of container tech by the way. Do you also run something like CoreOS, Kubernetes etc?

How do you currently manage the container part alongside KVM? Just Ansible?

Sorry for the long list of questions, I'm just trying to figure out how people use Mist.io in their everyday life. It's really important info for future iterations.

**Comment by svx** [comment]
Yeah more or less, our infra is too small to use something like Kubernetes, Mesos or Openstack, currently it is a mix Debian, Ubuntu and CoreOS.

Management is done via Ansible and some scripts.
