### ISSUE TITLE
auth with docker

### ISSUE THREAD

**Issue by Jdesk** [mistio/mist.io#666]
I'm going to put it right out there and say python is not my area of expertise - managing infrastructure is - and I think you guys officially outdid them all - and still can't believe your offering this essentially as opensource - this isn't so much an issue but more of a request (I know I could learn in a few hours - but apache isn't strong for me either - nginx is - docker is coming along nicely as well - but my only thing is - if i'm running this live - (i've only been running locally inside virtualbox with machine for a bit more control - I run 7 diff flavors of nix) - but I can't for the life of me track down the specific file used for frontend auth - I was thinking of just installing apache2-utils, nginx, and mistio via compose but that's like putting a bandaid to cover it up - i hate asking but my scowering of the search engines that now give us the opposite of what we look for - has forced me to. what file handles auth? meaning user auth.

**Comment by Jdesk** [comment]
i've literally searched using sublime3 - and I saw that node seemed to be handling auth via app config (and this was like two weeks ago) - via the ansible deploy - i have an instance sitting on ec2 with security policies to high hell only allowing traffic from my ip - still haven't put any keys on there - bc I'm still paranoid about security - especially if I'm gonna put 150 machines on there

**Comment by mgogoulos** [comment]
hi, mist.io open source comes as a standalone solution without auth features for now. It starts on 8000 on the localhost interface, but if you want to expose it to port 80 through nginx and also add http basic auth then have a look on this thread: https://github.com/mistio/mist.io/issues/517

The 'Login' button that is offered on the top right will log you on your account on the Saas - https://mist.io - in order to enable monitoring and see monitoring data for your servers. So you need to have a valid account with a plan in order to be able to use the monitoring features. Ansible is used to deploy the monitoring server (collectd) that mist.io uses. 

Regarding ssh, you need to use the private ssh key that is deployed on the server, and of course make sure that from the host you run mist.io you can connect to that machine. Double check that since if the port is closed or denied for the mist.io server it won't be able to connect. 

You can use the open source mist.io and enable monitoring on your servers through an account you have on the Saas, in that case you won't have to upload ssh keys on the Saas, and the servers will only receive monitoring data. You will be missing some features (scripts, logs mainly) but eventually most of the functionality will be also available on the open source version in the next few months. And indeed security is a top priority and the fact that the software is open source makes it more secure, since it is exposed to people that can audit the code and also developers are 'forced' to follow secure practices while coding.

Cheers

**Comment by mgogoulos** [comment]
Version 2 is out, comes with an easier installation process using Docker Compose and many new features, check updated instructions on https://github.com/mistio/mist.io

This includes user management - http://blog.mist.io/post/162083041316/our-biggest-mistio-open-source-release-yet
