### ISSUE TITLE
Everyone who can access the web dashboard can use your mist.io login

### ISSUE THREAD

**Issue by grepwood** [mistio/mist.io#717]
I have figured out that the mist.io user credentials are stored in plaintext in `db.yaml`.
This is quite dangerous (and potentially unauthorized), as anyone who stumbles upon the web dashboard will be able to use the currently authenticated account until it is removed from that file and the whole app is restarted.

**Comment by mgogoulos** [comment]
Hi, 

the email and API token for a user that is authenticated to the Saas needs to be stored on the local installation of mist.io somehow, otherwise you would need to provide it any time you visit the app. You are very right, you have to protect db.yaml file on your local directory where mist.io is installed, if you're on a server where other users have access as well. As long as other people have access to your folder, it wouldn't have a difference if the API was encrypted, since they would have access to the password that has been used to encrypt it. 

Unless you think there's an issue here, I'm going to close it. 

Thanks and regards,
Markos

**Comment by grepwood** [comment]
Yes, I think there is a security issue here. Protecting the db.yaml file is not a problem, but what is really the elephant in the room is that absolutely everyone can manage your VMs if they have as little as just the access to the web dashboard. That includes people who might not be authorized to handle your VMs.
This can be mitigated by having visitors authenticate against a local database, so that only after passing that they are allowed to manage the application connected to the SaaS and the VMs.

**Comment by mgogoulos** [comment]
Hi, 

we are in contact with multiple organizations that implement their own auth mechanisms above mist.io, since the project is open source people are free to use it the way they prefer. That said, there's a major milestone for the next 2 months that will bring more features from the Saas to the open source project, one of them being the addition of mongodb database. We are thinking of adding by default authentication there, taking under consideration requests as yours. 

Regards,
Markos
