### ISSUE TITLE
failed at buildout, ubuntu 16.04

### ISSUE THREAD

**Issue by junhuy** [mistio/mist.io#737]
./bin/buildout -v

We have the best distribution that satisfies 'mr.developer'.
Picked: mr.developer = 1.34
mr.developer: Queued 'deploy_collectd' for checkout.
mr.developer: Queued 'libcloud' for checkout.
mr.developer: Skipped checkout of existing package 'libcloud'.
mr.developer: Skipped checkout of existing package 'deploy_collectd'.
Installing 'zc.buildout', 'setuptools'.
We have the best distribution that satisfies 'zc.buildout>=2.5.1'.
Picked: zc.buildout = 2.5.1
We have a develop egg: setuptools 20.9.0
Adding find link 'https://pypi.python.org/packages/source/c/certifi/certifi-2016.2.28.tar.gz#md5=5d672aa766e1f773c75cfeccd02d3650' from setuptools 20.9.0
Adding find link 'https://pypi.python.org/packages/source/w/wincertstore/wincertstore-0.2.zip#md5=ae728f2f007185648d0c7a8679b361e2' from setuptools 20.9.0
Develop: '/home/tim/mist.io/.'
warning: no files found matching '_.ico' under directory 'mistio'
warning: no files found matching '_.png' under directory 'mistio'
warning: no files found matching '_.css' under directory 'mistio'
warning: no files found matching '_.gif' under directory 'mistio'
warning: no files found matching '_.jpg' under directory 'mistio'
warning: no files found matching '_.pt' under directory 'mistio'
warning: no files found matching '_.txt' under directory 'mistio'
warning: no files found matching '_.mak' under directory 'mistio'
warning: no files found matching '_.mako' under directory 'mistio'
warning: no files found matching '_.js' under directory 'mistio'
warning: no files found matching '_.html' under directory 'mistio'
warning: no files found matching '_.xml' under directory 'mistio'
Develop: '/home/tim/mist.io/src/libcloud'
no previously-included directories found matching 'libcloud/test/secrets.py'
Installing 'zc.recipe.egg'.
We have the best distribution that satisfies 'zc.recipe.egg>=2.0.0a3'.
Picked: zc.recipe.egg = 2.0.3
Installing 'collective.recipe.pip'.
We have the best distribution that satisfies 'collective.recipe.pip'.
Adding find link 'https://github.com/minddistrict/mr.scripty/archive/4bbfa2b48b7bc8a215c80a19e61ac39d0c9545aa.zip#egg=mr.scripty' from collective.recipe.pip 0.3.2
Picked: collective.recipe.pip = 0.3.2
pip.utils: lzma module is not available
pip.vcs: Registered VCS backend: git
pip.vcs: Registered VCS backend: hg
pip.vcs: Registered VCS backend: svn
pip.vcs: Registered VCS backend: bzr
pip._vendor.requests.packages.urllib3.util.retry: Converted retries value: Retry(total=0, connect=None, read=None, redirect=None) -> Retry(total=Retry(total=0, connect=None, read=None, redirect=None), connect=None, read=None, redirect=None)
pip._vendor.requests.packages.urllib3.util.retry: Converted retries value: Retry(total=0, connect=None, read=None, redirect=None) -> Retry(total=Retry(total=0, connect=None, read=None, redirect=None), connect=None, read=None, redirect=None)
While:
  Installing.
  Getting section pip.
  Initializing section pip.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/home/tim/mist.io/eggs/zc.buildout-2.5.1-py2.7.egg/zc/buildout/buildout.py", line 1992, in main
    getattr(buildout, command)(args)
  File "/home/tim/mist.io/eggs/zc.buildout-2.5.1-py2.7.egg/zc/buildout/buildout.py", line 550, in install
    [self[part]['recipe'] for part in install_parts]
  File "/home/tim/mist.io/eggs/zc.buildout-2.5.1-py2.7.egg/zc/buildout/buildout.py", line 1135, in **getitem**
    options._initialize()
  File "/home/tim/mist.io/eggs/zc.buildout-2.5.1-py2.7.egg/zc/buildout/buildout.py", line 1239, in _initialize
    self.initialize()
  File "/home/tim/mist.io/eggs/zc.buildout-2.5.1-py2.7.egg/zc/buildout/buildout.py", line 1248, in initialize
    self.recipe = recipe_class(buildout, name, self)
  File "/home/tim/mist.io/eggs/collective.recipe.pip-0.3.2-py2.7.egg/collective/recipe/pip/__init__.py", line 41, in **init**
    self.process()
  File "/home/tim/mist.io/eggs/collective.recipe.pip-0.3.2-py2.7.egg/collective/recipe/pip/**init**.py", line 68, in process
    self.options['eggs'] = "\n".join(sorted(set(eggs)))
  File "/home/tim/mist.io/eggs/zc.buildout-2.5.1-py2.7.egg/zc/buildout/buildout.py", line 1370, in **setitem**
    raise TypeError('Option values must be strings', value)
TypeError: ('Option values must be strings', u'PasteDeploy==1.5.2\nPasteScript==2.0.2\nPyYAML==3.11\nSphinx==1.3.5\namqp==1.4.6\nansible==1.9.3\napache-libcloud\nbehave==1.2.5\nbehaving==1.4.1\ncelery==3.1.17\ngevent-subprocess==0.1.1\ngevent==1.0.2\nnetaddr==0.7.18\nparamiko==1.16.0\npika==0.10.0\npycrypto==2.6.1\npyramid==1.4\npytest==2.8.7\npython-memcached==1.57\nrequests==2.7.0\nselenium==2.52.0\nsockjs-tornado==1.0.2\nsphinx-bootstrap-theme==0.4.7\nsphinx-rtd-theme==0.1.8\nsphinxcontrib-httpdomain==1.4.0\nwebsocket-client==0.29.0')

**Comment by jayala** [comment]
Having the same problem with Odroid C2 Ubuntu Xenial 16.04.
`An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/home/softec/mist.io/eggs/zc.buildout-2.5.1-py2.7.egg/zc/buildout/buildout.py", line 1992, in main
    getattr(buildout, command)(args)
  File "/home/softec/mist.io/eggs/zc.buildout-2.5.1-py2.7.egg/zc/buildout/buildout.py", line 550, in install
    [self[part]['recipe'] for part in install_parts]
  File "/home/softec/mist.io/eggs/zc.buildout-2.5.1-py2.7.egg/zc/buildout/buildout.py", line 1135, in __getitem__
    options._initialize()
  File "/home/softec/mist.io/eggs/zc.buildout-2.5.1-py2.7.egg/zc/buildout/buildout.py", line 1239, in _initialize
    self.initialize()
  File "/home/softec/mist.io/eggs/zc.buildout-2.5.1-py2.7.egg/zc/buildout/buildout.py", line 1248, in initialize
    self.recipe = recipe_class(buildout, name, self)
  File "/home/softec/mist.io/eggs/collective.recipe.pip-0.3.2-py2.7.egg/collective/recipe/pip/__init__.py", line 41, in __init__
    self.process()
  File "/home/softec/mist.io/eggs/collective.recipe.pip-0.3.2-py2.7.egg/collective/recipe/pip/__init__.py", line 68, in process
    self.options['eggs'] = "\n".join(sorted(set(eggs)))
  File "/home/softec/mist.io/eggs/zc.buildout-2.5.1-py2.7.egg/zc/buildout/buildout.py", line 1370, in __setitem__
    raise TypeError('Option values must be strings', value)
TypeError: ('Option values must be strings', u'PasteDeploy==1.5.2\nPasteScript==2.0.2\nPyYAML==3.11\nSphinx==1.3.5\namqp==1.4.6\nansible==1.9.3\napache-libcloud\nbehave==1.2.5\nbehaving==1.4.1\ncelery==3.1.17\ngevent-subprocess==0.1.1\ngevent==1.0.2\nnetaddr==0.7.18\nparamiko==1.16.0\npika==0.10.0\npycrypto==2.6.1\npyramid==1.4\npytest==2.8.7\npython-memcached==1.57\nrequests==2.7.0\nselenium==2.52.0\nsockjs-tornado==1.0.2\nsphinx-bootstrap-theme==0.4.7\nsphinx-rtd-theme==0.1.8\nsphinxcontrib-httpdomain==1.4.0\nwebsocket-client==0.29.0')`

**Comment by junhuy** [comment]
Does odroid support virtualization? Or you use it as controller only?

**Comment by jayala** [comment]
Only as a controller.

**Comment by mgogoulos** [comment]
Hi, will perform an installation on Ubuntu 16.04 and see what is creating the issue

**Comment by jayala** [comment]
Well, I managed to solve some of the problems, but now I'm stuck in mist.io installation.
The first problem: TypeError: ('Option values must be strings'...
I solved this by commenting the type validation it performs there because it is an unicode text not str, but stills valid..

The second problem: gevent==1.0.2
It tries to install this package and breaks because my odroid architecture (aarch64) failing to determinate it with the version of config it has(2008).
I manually installed it updating config.sub and config.guess and it worked.

The third problem: ValueError: too many values to unpack

An internal error occurred due to a bug in either zc.buildout or in a recipe being used:
Traceback (most recent call last):
  File "/home/softec/mist.io/eggs/zc.buildout-2.5.1-py2.7.egg/zc/buildout/buildout.py", line 1992, in main
    getattr(buildout, command)(args)
  File "/home/softec/mist.io/eggs/zc.buildout-2.5.1-py2.7.egg/zc/buildout/buildout.py", line 666, in install
    installed_files = self[part]._call(recipe.install)
  File "/home/softec/mist.io/eggs/zc.buildout-2.5.1-py2.7.egg/zc/buildout/buildout.py", line 1407, in _call
    return f()
  File "/home/softec/mist.io/eggs/zc.recipe.egg-2.0.3-py2.7.egg/zc/recipe/egg/egg.py", line 162, in install
    relative_paths=self._relative_paths,
  File "/home/softec/mist.io/eggs/zc.buildout-2.5.1-py2.7.egg/zc/buildout/easy_install.py", line 1107, in scripts
    for name, module_name, attrs in entry_points:
ValueError: too many values to unpack

The entry_points list:
`[u'mist.io', u'PasteScript', u'PasteDeploy==1.5.2', u'PasteScript==2.0.2', u'PyYAML==3.11', u'Sphinx==1.3.5', u'amqp==1.4.6', u'ansible==1.9.3', u'apache-libcloud', u'behave==1.2.5', u'behaving==1.4.1', u'celery==3.1.17', u'gevent-subprocess==0.1.1', u'gevent==1.0.2', u'netaddr==0.7.18', u'paramiko==1.16.0', u'pika==0.10.0', u'pycrypto==2.6.1', u'pyramid==1.4', u'pytest==2.8.7', u'python-memcached==1.57', u'requests==2.7.0', u'selenium==2.52.0', u'sockjs-tornado==1.0.2', u'sphinx-bootstrap-theme==0.4.7', u'sphinx-rtd-theme==0.1.8', u'sphinxcontrib-httpdomain==1.4.0', u'websocket-client==0.29.0', ('sphinx-apidoc', 'sphinx.apidoc', 'main'), ('sphinx-build', 'sphinx', 'main'), ('sphinx-quickstart', 'sphinx.quickstart', 'main'), ('sphinx-autogen', 'sphinx.ext.autosummary.generate', 'main'), ('behave', 'behave.__main__', 'main'), ('mailmock', 'behaving.mail.mock', 'main'), ('gcmmock', 'behaving.notifications.gcm.mock', 'main'), ('smsmock', 'behaving.sms.mock', 'main'), ('celery', 'celery.__main__', 'main'), ('celeryd', 'celery.__main__', '_compat_worker'), ('celeryd-multi', 'celery.__main__', '_compat_multi'), ('celerybeat', 'celery.__main__', '_compat_beat'), ('ptweens', 'pyramid.scripts.ptweens', 'main'), ('proutes', 'pyramid.scripts.proutes', 'main'), ('pshell', 'pyramid.scripts.pshell', 'main'), ('prequest', 'pyramid.scripts.prequest', 'main'), ('pviews', 'pyramid.scripts.pviews', 'main'), ('bfg2pyramid', 'pyramid.fixers.fix_bfg_imports', 'main'), ('pcreate', 'pyramid.scripts.pcreate', 'main'), ('pserve', 'pyramid.scripts.pserve', 'main'), ('py.test-2.7', 'pytest', 'main'), ('py.test', 'pytest', 'main'), ('mako-render', 'mako.cmd', 'cmdline'), ('pybabel', 'babel.messages.frontend', 'main'), ('pygmentize', 'pygments.cmdline', 'main')]`

Some of the items are text and others tuples..

**Comment by mgogoulos** [comment]
I now see that Ubuntu 16.04 - which has been released a few days ago- officially uses Python3 instead of Python2.7. This is a major change since mist.io is built for Python2.X and these two versions of Python unfortunately are incompatible...

That said, I would suggest that you try the buildout installation on a previous version of Ubuntu (eg Ubuntu 14/15), if you *must* run mist.io on Ubuntu 16.04 you can use the docker image - instructions on http://docs.mist.io/article/39-installation - until we make it working for python3 and Ubuntu 16.04.

**Comment by dalenoe** [comment]
Anyone had any luck with 16.04? Almost wish I wouldn't have upgraded now... lol

**Comment by suwidadi** [comment]
I'm trying with Ubuntu 14.04 no luck either... wonder what exact requirement to install ? i run exactly like the docs said but it keeps failing...

**Comment by mgogoulos** [comment]
Version 2 is out, comes with an easier installation process using Docker Compose and many new features, check updated instructions on https://github.com/mistio/mist.io
