### ISSUE TITLE
Unable to probe (KVM)

### ISSUE THREAD

**Issue by junhuy** [mistio/mist.io#743]
I am able to probe certain VMs but not all. Nothing seems to appear in the log too after pressing the probe button for those VMs. How should I trace where it went wrong as I do not know what IP should I use to access those VMs? Thanks.

**Comment by mgogoulos** [comment]
Do you see an ip on these machines? On the basic info tab you should be able to see a public ip and/or a private ip, if the KVM hypervisor is able to see traffic from these VMs

**Comment by junhuy** [comment]
No, not all of them. I am only able to see the ip for certain machines but not all. Some of the machines have no information at all just like the picture attached here.

![probe](https://cloud.githubusercontent.com/assets/11226538/14906325/33b02fb6-0df5-11e6-950e-05d96ec7d07d.png)

**Comment by mgogoulos** [comment]
Hi, 

the "probe" button will try to ssh the server (if it has an ssh key associated) and show basic uptime + load info, otherwise it will try to ping the server and return a small diagram with ping latency, if it can get replies on the pings. In both cases it is necessary that the server has an ip address.

 In the KVM case, they hypervisor has no direct way to receive information about the ips the VMs it hosts have, meaning that there is no way to ask the hypervisor via an API what ip address a VM has taken. It only keeps a track on what MAC address each VM has, this is specified on the XML configuration file of each VM. That said, mist.io tries to get the arp table from the hypervisor, and correlate MAC addresses (VMs) with the ip addresses in use. In most cases this will work, so it can show you a public or private ip/ips. Some times we have noticed that if the VM hasn't exchanged traffic with the hypervisor, that it's MAC address/addresses are not on the arp table, so mist.io will not show an ip.

**Comment by fuqqer** [comment]
The ARP table method will not work with a KVM/libvirt hypervisor when the network is set up as a bridge.

If the qemu-guest-agent is installed on VMs, it allows the following command to be run on a hypervisor to reliably get the VM IP:
virsh domifaddr $VMNAMEHERE --source=agent

**Comment by mgogoulos** [comment]
Do you think that's the case for all bridges? I have a bridged KVM setup and arp -an shows the mac/ips for my VMs. 

Wasn't aware of the virsh domifaddr command, we could use this one and the arp -an as a fallback when the command is not available on the system. 

Thanks for the comment!
