### ISSUE TITLE
MacOSX install fails

### ISSUE THREAD

**Issue by laurieodgers** [mistio/mist.io#887]
I have run the following commands to install mist.io:

```
sudo easy_install virtualenv
git clone https://github.com/mistio/mist.io.git
cd mist.io
virtualenv --no-site-packages .
./bin/python bootstrap.py
./bin/buildout -v
```

buildout fails with the following message:

```
Getting distribution for 'certifi'.
While:
  Installing mist.
  Getting distribution for 'certifi'.
Error: Can't download https://pypi.python.org/packages/source/c/certifi/certifi-2016.9.26.tar.gz#md5=baa81e951a29958563689d868ef1064d: 404 Not Found
```

**Comment by liGhun** [comment]
Same here on Debain/Raspberry Pi

**Comment by denisj07** [comment]
Same on Debian/Ubuntu

**Comment by Endag** [comment]
Same on Centos 7
Even after manual install as suggested denisj07 somehow still getting

> Getting required 'certifi'
  required by tornado 4.4.2.
We have no distributions for certifi that satisfies 'certifi'.

and then it trying to get it from that broken url

**Comment by holastickboy** [comment]
This is not unique to Mac OS, it appears to be happening on Linux too.  It's because the script is referencing an incorrect URL:

```
Getting distribution for 'certifi'.
Error: Can't download https://pypi.python.org/packages/source/c/certifi/certifi-2016.9.26.tar.gz#md5=baa81e951a29958563689d868ef1064d: 404 Not Found
```

**The correct location of the file above is actually:**
`https://pypi.python.org/packages/4f/75/e1bc6e363a2c76f8d7e754c27c437dbe4086414e1d6d2f6b2a3e7846f22b/certifi-2016.9.26.tar.gz#md5=baa81e951a29958563689d868ef1064d`

Need to track down the file where it references the incorrect URL and update with the correct one. The work around about manually installing certifi with `./bin/pip install certifi` worked for me in the meantime.

**Comment by mgogoulos** [comment]
Version 2 is out, comes with an easier installation process using Docker Compose and many new features, check updated instructions on https://github.com/mistio/mist.io
